"""
This type stub file was generated by pyright.
"""

from ._core import Rect, RectFile, RectFitResult, RectFlags_t, Vec2f, Vec2i, fit_rect_to_surface, get_score

__all__ = ["fit_rect_to_surface", "get_score", "RectFlags_t", "Vec2f", "Vec2i", "Rect", "RectFitResult", "RectFile"]
