"""
This type stub file was generated by pyright.
"""

from ._core import Rect, RectFile, RectFitResult, RectFlags_t, Vec2f, Vec2i, RectFitter

__all__ = ["RectFitter", "RectFlags_t", "Vec2f", "Vec2i", "Rect", "RectFitResult", "RectFile"]
