from collections.abc import Sequence
import enum
from typing import overload


class RectFitter:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, config: WeightConfig) -> None: ...

    @property
    def config(self) -> WeightConfig: ...

    @config.setter
    def config(self, arg: WeightConfig, /) -> None: ...

    def get_score(self, dims_surf: Vec2f, rect: Rect, out_result: RectFitResult) -> None: ...

    def fit_rect_to_surface(self, rects: Sequence[Rect], dims_surf: Vec2f, out_result: RectFitResult) -> int: ...

    def get_final_bounds(self, rect: Rect, tiling: Vec2f, inset: float, out_bounds: Rect) -> None: ...

    def get_final_transform(self, tex_size: Vec2f, rect: Rect, tiling: Vec2f, inset: float, rotation: int) -> list[float]: ...

class RectFlags_t(enum.Flag):
    enable_rotation = 1

    enable_reflection = 2

    alt_group = 4

    tile_x = 8

    tile_y = 16

    tile_x_y = 24

enable_rotation: RectFlags_t = RectFlags_t.enable_rotation

enable_reflection: RectFlags_t = RectFlags_t.enable_reflection

alt_group: RectFlags_t = RectFlags_t.alt_group

tile_x: RectFlags_t = RectFlags_t.tile_x

tile_y: RectFlags_t = RectFlags_t.tile_y

tile_x_y: RectFlags_t = RectFlags_t.tile_x_y

class Vec2f:
    def __init__(self, x: float, y: float) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    def swapped(self) -> Vec2f: ...

    def dot(self, arg: Vec2f, /) -> float: ...

    def normalized(self, arg: float, /) -> Vec2f: ...

class Vec2i:
    def __init__(self, x: int, y: int) -> None: ...

    @property
    def x(self) -> int: ...

    @x.setter
    def x(self, arg: int, /) -> None: ...

    @property
    def y(self) -> int: ...

    @y.setter
    def y(self, arg: int, /) -> None: ...

    def swapped(self) -> Vec2i: ...

class Rect:
    def __init__(self, flags: int, mins: Vec2f, maxs: Vec2f) -> None: ...

    @property
    def flags(self) -> int: ...

    @flags.setter
    def flags(self, arg: int, /) -> None: ...

    @property
    def mins(self) -> Vec2f: ...

    @mins.setter
    def mins(self, arg: Vec2f, /) -> None: ...

    @property
    def maxs(self) -> Vec2f: ...

    @maxs.setter
    def maxs(self, arg: Vec2f, /) -> None: ...

    def get_width(self) -> float: ...

    def get_height(self) -> float: ...

    def can_rotate(self) -> bool: ...

    def can_reflect(self) -> bool: ...

    def can_tile(self) -> bool: ...

    def can_tile_x(self) -> bool: ...

    def can_tile_y(self) -> bool: ...

    def is_alt_group(self) -> bool: ...

class WeightConfig:
    def __init__(self) -> None: ...

    @property
    def pow_cardinality(self) -> float: ...

    @pow_cardinality.setter
    def pow_cardinality(self, arg: float, /) -> None: ...

    @property
    def weight_dot(self) -> float: ...

    @weight_dot.setter
    def weight_dot(self, arg: float, /) -> None: ...

    @property
    def weight_scale(self) -> float: ...

    @weight_scale.setter
    def weight_scale(self, arg: float, /) -> None: ...

    @property
    def weight_tiling(self) -> float: ...

    @weight_tiling.setter
    def weight_tiling(self, arg: float, /) -> None: ...

    @property
    def error_margin(self) -> float: ...

    @error_margin.setter
    def error_margin(self, arg: float, /) -> None: ...

class RectFitResult:
    def __init__(self, rect_idx: int, rotated: bool) -> None: ...

    @property
    def rect_idx(self) -> int: ...

    @rect_idx.setter
    def rect_idx(self, arg: int, /) -> None: ...

    @property
    def tiling(self) -> Vec2f: ...

    @tiling.setter
    def tiling(self, arg: Vec2f, /) -> None: ...

    @property
    def rotated(self) -> bool: ...

    @rotated.setter
    def rotated(self, arg: bool, /) -> None: ...

    @property
    def score(self) -> float: ...

    @score.setter
    def score(self, arg: float, /) -> None: ...

class RectFile:
    def __init__(self, version: int, tex_size: Vec2i, rects: Sequence[Rect]) -> None: ...

    @property
    def flags(self) -> int: ...

    @flags.setter
    def flags(self, arg: int, /) -> None: ...

    @property
    def tex_size(self) -> Vec2i: ...

    @property
    def rects(self) -> list[Rect]: ...
